name: Continuous integration pipeline

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install pylint==2.17.2 black==23.3.0 ; fi
      - name: Format with black
        continue-on-error: true
        shell: bash
        id: black
        run: |
          python -m black --version
          python -m black --line-length=100 --check .

      - name: Lint with pylint
        continue-on-error: true
        shell: bash
        id: pylint
        run: |
          touch $( pwd )/samples/__init__.py
          python -m pylint --version
          python -m pylint $( pwd )/samples --ignore-paths samples/tests 

      - name: Check if any linting step failed
        shell: bash
        if: steps.black.outcome != 'success' || steps.pylint.outcome != 'success'
        run: |
          if [ "${{ steps.black.outcome }}" != "success" ]; then
            echo "Linting with black failed!"
          fi
          if [ "${{ steps.pylint.outcome }}" != "success" ]; then
            echo "Linting with pylint failed!"
          fi
          # If this step is run, at least one linting tool failed.
          exit 1

  unit-tests:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ./samples:.
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install pytest==7.3.1 ; fi
      - name: Test with pytest
        run: |
          python -m pytest ./samples