name: Continuous integration pipeline

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: "3.12"
          enable-cache: true
      - name: Install dependencies
        run: uv sync --locked
      - name: Check formatting with ruff
        run: uv run ruff format --check .
      - name: Lint with ruff
        run: uv run ruff check .

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: "3.12"
          enable-cache: true
      - name: Install dependencies
        run: uv sync --locked
      - name: Test with pytest
        run: uv run pytest src/samples